version: 2
jobs:
  test:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.15-browsers
    environment:
      AWSCLI_LATEST_VERSION: 1.16.207
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true 
      - restore_cache:
          key: circle-ci-crawling-test-{{ checksum "package-lock.json" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Check Version
          command: |
            node index.js $AWSCLI_LATEST_VERSION
            latest_version=$(cat version)
            if [ "$AWSCLI_LATEST_VERSION" != "$latest_version" ]; then  
              sed -i -e "s/AWSCLI_LATEST_VERSION: [0-9.][0-9.]*$/AWSCLI_LATEST_VERSION: $latest_version/" .circleci/config.yml
              git config --global user.name "Takafumi Umemoto"
              git config --global user.email "takafumi.umemoto@gmail.com"
              git add .circleci/config.yml
              git commit -m "Update $latest_version"
              git push origin master
            fi
      - save_cache:
          key: circle-ci-crawling-test-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules
workflows:
  version: 2
  commit:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
  regular_check:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
