version: 2
jobs:
  test:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.15-browsers
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true 
      - restore_cache:
          key: circle-ci-crawling-test-{{ checksum "package-lock.json" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Check Version
          command: |
            node index.js 1.16.81
            if [ $? -ne 0 ]; then
              exit 1
            fi
      - save_cache:
          key: circle-ci-crawling-test-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules
workflows:
  version: 2
  commit:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
  regular_check:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
